07.11.23 12:27 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
07.11.23 12:27 - [33mPress CTRL+C to quit[0m
07.11.23 12:27 -  * Restarting with stat
07.11.23 12:27 -  * Debugger is active!
07.11.23 12:27 -  * Debugger PIN: 133-739-974
07.11.23 12:27 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
07.11.23 12:27 - [33mPress CTRL+C to quit[0m
07.11.23 12:28 - 127.0.0.1 - - [07/Nov/2023 12:28:01] "GET / HTTP/1.1" 200 -
07.11.23 12:28 - 127.0.0.1 - - [07/Nov/2023 12:28:02] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
07.11.23 12:28 - 127.0.0.1 - - [07/Nov/2023 12:28:07] "GET /create HTTP/1.1" 200 -
07.11.23 12:28 - note "try1" was created
07.11.23 12:28 - Exception on /create [POST]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/limudim/note-app-project/app/app.py", line 42, in create
    flash(f'"{title}" was created', 'success')
  File "/home/user/.local/lib/python3.10/site-packages/flask/helpers.py", line 328, in flash
    session["_flashes"] = flashes
  File "/home/user/.local/lib/python3.10/site-packages/flask/sessions.py", line 97, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
07.11.23 12:28 - 127.0.0.1 - - [07/Nov/2023 12:28:23] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
07.11.23 12:28 - 127.0.0.1 - - [07/Nov/2023 12:28:27] "GET /main HTTP/1.1" 200 -
07.11.23 12:28 - 127.0.0.1 - - [07/Nov/2023 12:28:33] "GET /read/try1 HTTP/1.1" 200 -
07.11.23 12:28 - 127.0.0.1 - - [07/Nov/2023 12:28:35] "GET /main HTTP/1.1" 200 -
07.11.23 12:28 - 127.0.0.1 - - [07/Nov/2023 12:28:36] "GET /update/try1 HTTP/1.1" 200 -
07.11.23 12:28 - changes saved to "try1"
07.11.23 12:28 - Exception on /update/try1 [POST]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/limudim/note-app-project/app/app.py", line 68, in update
    flash(f'changes saved to "{title}"', 'success')
  File "/home/user/.local/lib/python3.10/site-packages/flask/helpers.py", line 328, in flash
    session["_flashes"] = flashes
  File "/home/user/.local/lib/python3.10/site-packages/flask/sessions.py", line 97, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
07.11.23 12:28 - 127.0.0.1 - - [07/Nov/2023 12:28:47] "[35m[1mPOST /update/try1 HTTP/1.1[0m" 500 -
07.11.23 12:28 - 127.0.0.1 - - [07/Nov/2023 12:28:51] "GET /main HTTP/1.1" 200 -
07.11.23 12:28 - 127.0.0.1 - - [07/Nov/2023 12:28:54] "GET /delete/try1 HTTP/1.1" 200 -
07.11.23 12:28 - note "try1" was deleted
07.11.23 12:28 - Exception on /delete/try1 [POST]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/limudim/note-app-project/app/app.py", line 82, in delete
    flash(f'note "{title}" was deleted', 'success')
  File "/home/user/.local/lib/python3.10/site-packages/flask/helpers.py", line 328, in flash
    session["_flashes"] = flashes
  File "/home/user/.local/lib/python3.10/site-packages/flask/sessions.py", line 97, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
07.11.23 12:28 - 127.0.0.1 - - [07/Nov/2023 12:28:59] "[35m[1mPOST /delete/try1 HTTP/1.1[0m" 500 -
07.11.23 12:29 - 127.0.0.1 - - [07/Nov/2023 12:29:03] "GET /main HTTP/1.1" 200 -
07.11.23 12:29 - 127.0.0.1 - - [07/Nov/2023 12:29:05] "GET /create HTTP/1.1" 200 -
07.11.23 12:29 - 127.0.0.1 - - [07/Nov/2023 12:29:14] "GET /main HTTP/1.1" 200 -
07.11.23 12:29 - 127.0.0.1 - - [07/Nov/2023 12:29:20] "GET /create HTTP/1.1" 200 -
07.11.23 12:29 - note "a" was created
07.11.23 12:29 - Exception on /create [POST]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/limudim/note-app-project/app/app.py", line 42, in create
    flash(f'"{title}" was created', 'success')
  File "/home/user/.local/lib/python3.10/site-packages/flask/helpers.py", line 328, in flash
    session["_flashes"] = flashes
  File "/home/user/.local/lib/python3.10/site-packages/flask/sessions.py", line 97, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
07.11.23 12:29 - 127.0.0.1 - - [07/Nov/2023 12:29:26] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
07.11.23 12:29 - note "a" was created
07.11.23 12:29 - Exception on /create [POST]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/limudim/note-app-project/app/app.py", line 42, in create
    flash(f'"{title}" was created', 'success')
  File "/home/user/.local/lib/python3.10/site-packages/flask/helpers.py", line 328, in flash
    session["_flashes"] = flashes
  File "/home/user/.local/lib/python3.10/site-packages/flask/sessions.py", line 97, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
07.11.23 12:29 - 127.0.0.1 - - [07/Nov/2023 12:29:33] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
07.11.23 12:29 - 127.0.0.1 - - [07/Nov/2023 12:29:35] "GET /main HTTP/1.1" 200 -
07.11.23 12:29 - 127.0.0.1 - - [07/Nov/2023 12:29:42] "[33mGET /ma HTTP/1.1[0m" 404 -
07.11.23 12:30 - 127.0.0.1 - - [07/Nov/2023 12:30:05] "GET /read/a HTTP/1.1" 200 -
07.11.23 12:30 - Exception on /read/try [GET]
Traceback (most recent call last):
  File "/home/user/limudim/note-app-project/app/app.py", line 50, in read
    with open(f'notes/{title}.txt', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'notes/try.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/limudim/note-app-project/app/app.py", line 54, in read
    flash(f'"{title}" not found', 'error')
  File "/home/user/.local/lib/python3.10/site-packages/flask/helpers.py", line 328, in flash
    session["_flashes"] = flashes
  File "/home/user/.local/lib/python3.10/site-packages/flask/sessions.py", line 97, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
07.11.23 12:30 - 127.0.0.1 - - [07/Nov/2023 12:30:10] "[35m[1mGET /read/try HTTP/1.1[0m" 500 -
07.11.23 12:33 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
07.11.23 12:33 - [33mPress CTRL+C to quit[0m
07.11.23 12:33 -  * Restarting with stat
07.11.23 12:33 -  * Debugger is active!
07.11.23 12:33 -  * Debugger PIN: 133-739-974
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:10] "GET /main HTTP/1.1" 200 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:12] "GET /main HTTP/1.1" 200 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:14] "GET /main HTTP/1.1" 200 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:16] "GET /read/a HTTP/1.1" 200 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:16] "GET /main HTTP/1.1" 200 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:18] "GET /update/a HTTP/1.1" 200 -
07.11.23 12:33 - Changes saved to "a"
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:21] "[35m[1mPOST /update/a HTTP/1.1[0m" 500 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:21] "GET /update/a?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:21] "GET /update/a?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:21] "GET /update/a?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:21] "[36mGET /update/a?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:29] "GET /main HTTP/1.1" 200 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:30] "GET /delete/a HTTP/1.1" 200 -
07.11.23 12:33 - Note "a" was deleted
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:31] "[35m[1mPOST /delete/a HTTP/1.1[0m" 500 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:31] "GET /delete/a?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:31] "GET /delete/a?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:31] "GET /delete/a?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:31] "[36mGET /delete/a?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
07.11.23 12:33 - 127.0.0.1 - - [07/Nov/2023 12:33:35] "GET / HTTP/1.1" 200 -
07.11.23 12:35 -  * Detected change in '/home/user/limudim/note-app-project/app/app2.py', reloading
07.11.23 12:35 -  * Restarting with stat
07.11.23 12:35 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
07.11.23 12:35 - [33mPress CTRL+C to quit[0m
07.11.23 12:35 - 127.0.0.1 - - [07/Nov/2023 12:35:23] "GET / HTTP/1.1" 200 -
07.11.23 12:35 - 127.0.0.1 - - [07/Nov/2023 12:35:25] "GET /create HTTP/1.1" 200 -
07.11.23 12:35 - Note "a" was created
07.11.23 12:35 - Exception on /create [POST]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/limudim/note-app-project/app/app2.py", line 42, in create
    flash(f'"{title}" was created', 'success')
  File "/home/user/.local/lib/python3.10/site-packages/flask/helpers.py", line 328, in flash
    session["_flashes"] = flashes
  File "/home/user/.local/lib/python3.10/site-packages/flask/sessions.py", line 97, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
07.11.23 12:35 - 127.0.0.1 - - [07/Nov/2023 12:35:31] "[35m[1mPOST /create HTTP/1.1[0m" 500 -
07.11.23 12:35 - 127.0.0.1 - - [07/Nov/2023 12:35:36] "GET / HTTP/1.1" 200 -
07.11.23 12:35 - 127.0.0.1 - - [07/Nov/2023 12:35:54] "GET /update/a HTTP/1.1" 200 -
07.11.23 12:36 - Changes saved to "a"
07.11.23 12:36 - Exception on /update/a [POST]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/limudim/note-app-project/app/app2.py", line 68, in update
    flash(f'Changes saved to "{title}"', 'success')
  File "/home/user/.local/lib/python3.10/site-packages/flask/helpers.py", line 328, in flash
    session["_flashes"] = flashes
  File "/home/user/.local/lib/python3.10/site-packages/flask/sessions.py", line 97, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
07.11.23 12:36 - 127.0.0.1 - - [07/Nov/2023 12:36:02] "[35m[1mPOST /update/a HTTP/1.1[0m" 500 -
07.11.23 12:36 - 127.0.0.1 - - [07/Nov/2023 12:36:08] "GET / HTTP/1.1" 200 -
07.11.23 12:36 - 127.0.0.1 - - [07/Nov/2023 12:36:10] "GET / HTTP/1.1" 200 -
07.11.23 12:36 - 127.0.0.1 - - [07/Nov/2023 12:36:13] "GET /update/a HTTP/1.1" 200 -
07.11.23 12:36 - Changes saved to "a"
07.11.23 12:36 - Exception on /update/a [POST]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/limudim/note-app-project/app/app2.py", line 68, in update
    flash(f'Changes saved to "{title}"', 'success')
  File "/home/user/.local/lib/python3.10/site-packages/flask/helpers.py", line 328, in flash
    session["_flashes"] = flashes
  File "/home/user/.local/lib/python3.10/site-packages/flask/sessions.py", line 97, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
07.11.23 12:36 - 127.0.0.1 - - [07/Nov/2023 12:36:17] "[35m[1mPOST /update/a HTTP/1.1[0m" 500 -
07.11.23 12:36 - 127.0.0.1 - - [07/Nov/2023 12:36:19] "GET / HTTP/1.1" 200 -
